### PR TITLE
Switch to Meson build system

### LINKED ISSUE #19: Switch to `meson` or `cmake` build systems
Working on this now. Things were so much easier in FontForge project when we ditched GNU Autotools. I'm getting annoyed just working with it now and it's impeding my work, so I'm switching to one of these, depending on which I succeed with first.

### PR DESCRIPTION
**Pull request by ctrlcctrlv**
This was a massive amount of work.

image

Closes #19.

I hope @dankamongmen and @knok are OK with it.

This does two things:

* switches us to a Meson build system
* deletes all remnants of GNU Autotools in the core library

Writing this was useful for me, as it helped me figure out everything the library does and get very deep into its compilation process.  I understand well what we have and what's missing now.

You might notice a lot of source code changes. These are almost all removals of `#if(def)` statements which were useless. The other branch did not work in every case I removed. Just a bunch of promises that couldn't be kept, and GNU Autotools seems to nudge people into adding all these silly `#ifdef`'s even though it's impossible to build this without `stdio.h` etc it's still including `HAVE_STDIO_H`, `STDC_HEADERS`.

Here's my to-do list before merge:

- [x] remove GNU Autotools from `php`, `ruby` etc directories, add `meson.build`
- [ ] ditto for `examples`
- [x] document the new build procedure. it's simple, basic Meson build now with a build directory and `ninja`
- [x] update GitHub actions workflow

### CODE REVIEW

**Comment by orbea** [comment]
Please don't choose meson, autotools is much better. Or if you want another build system try sofort.

https://dev.midipix.org/zippy/sofort

**Comment by dankamongmen** [comment]
i'm a cmake man myself, but i'm happy to take a look through this if you feel the need. i wouldn't be able to get to it until this evening at the earliest. if you feel confident merging sans review, i have no problem with that.

**Comment by ctrlcctrlv** [comment]
@dankamongmen I almost went for cmake because it's what FontForge uses, but this is almost done and works fine. I wanted to port the existing Autotools `configure.ac` one for one which I think would be more difficult with cmake, but maybe not. 

Sofort is not widely used and its README is not correctly formatted, so that's not happening. The idea is to use a build system as well known as Autotools without the headaches of Autotools.

**Comment by ctrlcctrlv** [comment]
Oh, @orbea is the Slackware maintainer I emailed last night, that's why they prefer Autotools, heh. Slackware is very much in the past when it comes to these things, so I don't mind making an executive decision to use Meson. If they update they update, I'm not spending another 2 hours "debugging" something that was actually an Autotools error while trying to work on #15.

**Comment by ctrlcctrlv** [comment]
In any event Slackware can still use 1.9 with the CVE fixes, and we might consider backporting future CVE's to 1.9, while 2.0 can be the new version kitty will rely on.

**Comment by knok** [comment]
I'm not familier with meson, however at least debhelper suppots it so to build debian package, it seems no matter.
But I don't know about other platform, at least NetBSD pkgsrc supports libsixel, I need to confirm their maintaner's opinion.

**Comment by ctrlcctrlv** [comment]
It's widely used, and packaged in NetBSD: https://ftp.netbsd.org/pub/pkgsrc/current/pkgsrc/devel/meson/README.html

[NetBSD wiki contains instructions](https://wiki.netbsd.org/pkgsrc/how_to_convert_autotools_to_meson/) and notes:

> GNU's build system ("autotools", ./configure, etc) was previously the main one used by most of the open source world. However, lots of high profile projects (GNOME, etc) have been switching from it to a new python-based one, called meson.

Which is my main motivation, as it has lots of obvious benefits.

**Comment by dankamongmen** [comment]
> @dankamongmen I almost went for cmake because it's what FontForge uses, but this is almost done and works fine. I wanted to port the existing Autotools `configure.ac` one for one which I think would be more difficult with cmake, but maybe not.

to be clear, i'm pleased with any move =] hate running configure scripts that take longer than the actual compilation. good work!

**Comment by ctrlcctrlv** [comment]
@dankamongmen Thanks! It's so much faster now indeed.

**Comment by orbea** [comment]
> Sofort is not widely used and its README is not correctly formatted, so that's not happening.

The README seems to be a pagure bug and it is actually formatted correctly as can be seen in the following link.

https://dev.midipix.org/zippy/sofort/raw/main/f/README.SOFORT

Meson has inherent problems with cross compile (This is a problem with midipix for example) and fails at extremely basic things like supporting `--datarootdir` and `--docdir`. It also adds a hard dependency on python which itself has such a hopeless build system that sbpython now exists.

https://dev.midipix.org/python/sbpython3

Cmake has lot of problems with projects having to reinvent the wheel with things in regards to creating pkg-config files which most cmake projects get wrong among many other issues. It also adds a dependency on C++ which seems in poor taste for what is primarily a C project.

I think autotools is a perfectly fine build system which reliably works when done correctly. Sofort is arguably a much cleaner approach, but it is indeed not used much outside of midipix projects yet.

**Comment by ctrlcctrlv** [comment]
I think this is similar to the Sysvinit / Systemd debate, which showed that Sysvinit has a few very dedicated fans. In any case, libsixel is hardly on the leading edge of community-wide switch over to Cmake/Meson, if anything we are far behind the eight ball. In the process of writing this patch I referred to `meson.build` files from projects as diverse as Mesa, `irssi` and GIMP, all of which were helpful.

You seem to hate it a lot, nothing I can do about that, and clearly have preference for obscure projects, also nothing I can do about that.

**Comment by orbea** [comment]
> You seem to hate it a lot, nothing I can do about that, and clearly have preference for obscure projects, also nothing I can do about that.

I resent the false strawman argument. I just don't want to lose a working build system for something that will have significant drawbacks, its painful as a package maintainer.

**Comment by ctrlcctrlv** [comment]
I resent being told it would be of benefit to switch to build systems used by a few projects just because you like them, when the goal here is to change the build system such that users and packagers are likely to have experience with it equal to what they had with Autotools.

The Meson build is far faster than the Autotools build, so I don't see a reason not to switch. Given how many large projects have, the question is whether these "significant drawbacks" really exist, and I find that they do ont.

**Comment by ctrlcctrlv** [comment]
OK, this is done. :-)

I decided to leave the OpenGL example alone. It's fine to have an Autotools example that's not built by default. Will squash merge after check completes.

**Comment by orbea** [comment]
> @orbea is the Slackware maintainer

No longer the case, good job scaring away your users.

**Comment by ctrlcctrlv** [comment]
That's fine, when it's an optional build dependency of Kitty someone else will probably adopt the package if they want the feature.

Or not.

Go troll the GIMP/mesa/irssi issue trackers, they switched long before this project did. And it's more likely someone there will care enough to actually argue with you.

**Comment by ctrlcctrlv** [comment]
Uh oh, [the calls are coming from inside the house](https://mirror.slackbuilds.org/slackware/slackware-current/source/x/mesa/mesa.SlackBuild)!

> ```
> mkdir meson-build
> cd meson-build
> meson setup \
> --prefix=/usr \
> ...
> ```

Seems other Slackware maintainers have figured it out. :joy:

**Comment by midipix** [comment]
> The README seems to be a pagure bug and it is actually formatted correctly as can be seen in the following link.
> 
> https://dev.midipix.org/zippy/sofort/raw/main/f/README.SOFORT

Indeed a pagure bug, will report this upstream; in the meantime you can view the README using the above link. Or, even better, build from source any of the projects that use sofort (for instance https://dev.midipix.org/cross/slibtool) and see what the user experience is like.

I doubt any of the above will result in a change in your decision to use meson and do not expect or suggest that you put any more time into this.

Do note, however, that meson has clear disadvantages when it comes to cross-compilation, which are expressly noted in the meson documentation. One aim of sofort was to provide a familiar ./configure && make semantics while turning cross-compilation into the first-class case and native compilation into a trivial case of cross-compilation. Sofort also provides simple configure-time tests for detecting features of the host system (like type size, sysroot, etc.) that meson requires you to define per-target.

PS. incidentally, sofort is also considerably faster than autotools and works out of the box on minimal posix systems. But again, you've already made up your mind, so please consider this comment merely informational.

**Comment by ctrlcctrlv** [comment]
@midipix Thanks for the information! I'll consider it for another project, or perhaps even this one in future, especially for this one if it becomes more well known. I don't think cross-compilation is a huge need for this project, and it's supported to a degree in latest Meson releases, which may be enough (to be fair, I did not try a cross-compiled build). The WIC support has been disabled since 2014 (see a9df1893b321ada792181238d3276e0de80392c0), so MinGW cross-compilation isn't needed, and I'm not sure it'll ever come back.

Mostly, as I wrote, I didn't want to inconvenience people by using a not too well known build system, especially if problems arise. Although, perhaps because it uses traditional `./configure; make` it wouldn't have been too big an inconvenience. I also didn't mean to imply I don't think sofort is a _good_ build system (obviously don't have an opinion on that as I haven't tried it).

**Comment by midipix** [comment]
@ctrlcctrlv fair enough, and thank you for taking the time to look into this! Should you decide to use sofort for either libsixel or any other project, please feel welcome to let me know here (or on irc) and I'll be happy to help.

**Pull request merged**
