### PR TITLE
Meson cleanup

### PR DESCRIPTION
**Pull request by eli-schwartz**
Just a few quality of life improvements for more idiomatic meson.build

### CODE REVIEW

**Review by dankamongmen — APPROVED** [review]
looks great, thanks!

**Comment by dankamongmen** [comment]
we're hitting #43 now

**Comment by eli-schwartz** [comment]
Eep, sorry, but also #42 seems wrong as the file `/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf.h` is indeed meant to be included via `gdk-pixbuf/gdk-pixbuf.h`

On the other hand  `#if HAVE_JPEG` was indeed a bug exposed by actually enabling jpeg when detected via auto mode.

You could use conf.set10() but you'll need to decide between sometimes using `#if` and sometimes using `#ifdef`, yay for legacy...

**Comment by dankamongmen** [comment]
> Eep, sorry, but also #42 seems wrong as the file `/usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixbuf.h` is indeed meant to be included via `gdk-pixbuf/gdk-pixbuf.h`

yep, realized, hence #43, which you resolved with #44 =]

**Pull request merged**
